DROP TABLE IF EXISTS events CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS categories CASCADE;
DROP TABLE IF EXISTS requests CASCADE;
DROP TABLE IF EXISTS compilations CASCADE;

CREATE TABLE IF NOT EXISTS users (
id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
name VARCHAR(256) NOT NULL,
email VARCHAR(256) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS categories (
id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
name VARCHAR(64) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS compilations(
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    pinned BOOLEAN NOT NULL,
    title VARCHAR(64) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS events (
id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
annotation VARCHAR(2024) NOT NULL,
category_id BIGINT NOT NULL,
created_on TIMESTAMP WITHOUT TIME ZONE NOT NULL,
description VARCHAR(7000) NOT NULL,
event_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
initiator_id BIGINT NOT NULL,
lat FLOAT NOT NULL,
lon FLOAT NOT NULL,
paid BOOLEAN NOT NULL,
participant_limit INTEGER NOT NULL,
published_on TIMESTAMP WITHOUT TIME ZONE,
request_moderation BOOLEAN NOT NULL,
state VARCHAR(16) NOT NULL,
title VARCHAR(128) NOT NULL,
compilation_id BIGINT,
CONSTRAINT EVENTS_USER_ID_FK FOREIGN KEY (initiator_id) REFERENCES users(id) ON DELETE CASCADE,
CONSTRAINT EVENTS_CATEGORY_ID_FK FOREIGN KEY (category_id) REFERENCES categories(id),
CONSTRAINT EVENTS_COMPILATION_ID_FK FOREIGN KEY (compilation_id) REFERENCES compilations(id)
);

CREATE TABLE IF NOT EXISTS requests (
id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
created TIMESTAMP WITHOUT TIME ZONE NOT NULL,
event_id BIGINT NOT NULL,
requester_id BIGINT NOT NULL,
status VARCHAR(16) NOT NULL,
CONSTRAINT REQUESTS_REQUESTER_FK FOREIGN KEY (requester_id) REFERENCES users(id),
CONSTRAINT REQUESTS_EVENT_ID_FK FOREIGN KEY (event_id) REFERENCES events(id)
);